on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - run: noir --version

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - run: noir --version

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - run: noir --version
